/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.login;

import java.awt.Color;

/**
 *
 * @author INTEL
 */
public class Login extends javax.swing.JFrame {

    int xMouse, yMouse;
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        usuario = new javax.swing.JTextField();
        contraseña = new javax.swing.JPasswordField();
        separador1 = new javax.swing.JSeparator();
        separador2 = new javax.swing.JSeparator();
        sesion = new javax.swing.JLabel();
        textocamelot = new javax.swing.JLabel();
        bedi = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        btnsalir = new javax.swing.JPanel();
        lblexit = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        lblcontraseña = new javax.swing.JLabel();
        loginbtn = new javax.swing.JPanel();
        lblentrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        usuario.setForeground(new java.awt.Color(204, 204, 204));
        usuario.setText("ingrese nombre de usuario");
        usuario.setBorder(null);
        usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usuarioMousePressed(evt);
            }
        });
        background.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 240, 30));

        contraseña.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contraseña.setForeground(new java.awt.Color(204, 204, 204));
        contraseña.setText("********");
        contraseña.setBorder(null);
        contraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contraseñaMousePressed(evt);
            }
        });
        background.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 240, 30));
        background.add(separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 240, 10));
        background.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 240, 10));

        sesion.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        sesion.setText("INICIAR SESIÓN");
        background.add(sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 180, 70));

        textocamelot.setFont(new java.awt.Font("Roboto Black", 1, 30)); // NOI18N
        textocamelot.setForeground(new java.awt.Color(0, 102, 102));
        textocamelot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textocamelot.setText("CAMELOT SINGULARITY");
        background.add(textocamelot, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 380, 140));

        bedi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/avatar82.png"))); // NOI18N
        background.add(bedi, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 350, 160));

        fondo.setForeground(new java.awt.Color(0, 102, 102));
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/photo_2022-08-05_01-30-25.jpg"))); // NOI18N
        background.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 380, 500));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/command seal.png"))); // NOI18N
        background.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 150, 140));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setForeground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        lblexit.setFont(new java.awt.Font("Roboto", 0, 30)); // NOI18N
        lblexit.setForeground(new java.awt.Color(0, 51, 51));
        lblexit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblexit.setText("X");
        lblexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblexitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblexitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblexitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnsalirLayout = new javax.swing.GroupLayout(btnsalir);
        btnsalir.setLayout(btnsalirLayout);
        btnsalirLayout.setHorizontalGroup(
            btnsalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnsalirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblexit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnsalirLayout.setVerticalGroup(
            btnsalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblexit, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 750, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        background.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 40));

        lblusuario.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblusuario.setText("USUARIO");
        background.add(lblusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        lblcontraseña.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblcontraseña.setText("CONTRASEÑA");
        background.add(lblcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        loginbtn.setBackground(new java.awt.Color(0, 102, 102));
        loginbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginbtnMouseExited(evt);
            }
        });

        lblentrar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblentrar.setForeground(new java.awt.Color(255, 255, 255));
        lblentrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblentrar.setText("ENTRAR");
        lblentrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblentrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblentrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblentrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblentrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout loginbtnLayout = new javax.swing.GroupLayout(loginbtn);
        loginbtn.setLayout(loginbtnLayout);
        loginbtnLayout.setHorizontalGroup(
            loginbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblentrar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        loginbtnLayout.setVerticalGroup(
            loginbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblentrar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        background.add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void lblexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblexitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblexitMouseClicked

    private void lblexitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblexitMouseEntered
        btnsalir.setBackground(Color.red);
        lblexit.setForeground(Color.white);
        
    }//GEN-LAST:event_lblexitMouseEntered

    private void lblexitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblexitMouseExited
        btnsalir.setBackground(Color.white);
        lblexit.setForeground(new Color(0,51,51));
    }//GEN-LAST:event_lblexitMouseExited
//cargando
    private void lblentrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblentrarMouseEntered
        loginbtn.setBackground(Color.white);
        lblentrar.setForeground(new Color(0,102,102));
    }//GEN-LAST:event_lblentrarMouseEntered

    private void lblentrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblentrarMouseExited
        loginbtn.setBackground(new Color(0,102,102));
        lblentrar.setForeground(Color.white);
    }//GEN-LAST:event_lblentrarMouseExited

    private void loginbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnMouseEntered
        
    }//GEN-LAST:event_loginbtnMouseEntered

    private void loginbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnMouseExited
        
    }//GEN-LAST:event_loginbtnMouseExited

    private void usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioMousePressed
        if(usuario.getText().equals("ingrese nombre de usuario")){
            
            usuario.setText("");
            usuario.setForeground( Color.black);
            
        }
        
        if(String.valueOf(contraseña.getPassword()).isEmpty()){
            contraseña.setText("********");
            contraseña.setForeground(Color.gray);
        }
                
    }//GEN-LAST:event_usuarioMousePressed

    private void contraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contraseñaMousePressed
        if(String.valueOf(contraseña.getPassword()).equals("********")){
            contraseña.setText("");
            contraseña.setForeground( Color.black);
        }
        
        if(usuario.getText().isEmpty()){
            usuario.setText("ingrese nombre de usuario");
            usuario.setForeground(Color.gray);
        }
                
    }//GEN-LAST:event_contraseñaMousePressed

    private void lblentrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblentrarMouseClicked
        javax.swing.JOptionPane.showMessageDialog(this,"intento de login con los datos:\nUsuario: "+usuario.getText()+"\nContraseña: "+ String.valueOf(contraseña.getPassword()),"LOGIN",javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_lblentrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel bedi;
    private javax.swing.JPanel btnsalir;
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel header;
    private javax.swing.JLabel lblcontraseña;
    private javax.swing.JLabel lblentrar;
    private javax.swing.JLabel lblexit;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JPanel loginbtn;
    private javax.swing.JLabel logo;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JLabel sesion;
    private javax.swing.JLabel textocamelot;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
